#!/bin/bash
VERSION="0.1"
echo "Welcome to ROM Unzipper by LiteApplication"
ubin="/usr/bin"
wd=$(pwd)
quit() {
  exit 0
}
echo  "Checking root access..."
if [[ $EUID -ne 0 ]]; then
   echo "    This script must be run as root" 1>&2
   exit 1
fi

echo "Checking dependances..."
sudo apt-get update -qq >/dev/null 
if ! command -v python3 &>/dev/null; then
    echo "    Installing python3..."
    sudo apt-get install python3 python -qq > /dev/null
fi
if ! command -v git &>/dev/null; then
    echo "    Installing git..."
    sudo apt-get install git -qq > /dev/null
fi
if ! command -v brotli &>/dev/null; then
    echo "    Installing brotli..."
    sudo apt-get install brotli -qq > /dev/null
fi
rm -fr files
echo "Downloading program..."
mkdir files
cd files
git clone https://github.com/LiteApplication/rom-unzip.git --quiet
echo "Moving program..."
cd rom-unzip
mv src/* ../
cd ..
rm -fr rom-unzip
mkdir rom
cd $wd
sudo $ubin/python3 selectRom.py
quit
