#!/bin/bash
VERSION="0.1"
echo "Welcome to ROM Unzipper by LiteApplication"
if (whoami != root)
  then echo "You have to run this script as root. \n Try sudo ./1click"
  exit 1

echo "Checking dependances..."
if command -v python3 &>/dev/null; then
    echo "    Python 3 is installed"
else
    echo "    Installing python3..."
    sudo sudo apt-get install python3 python -qq > /dev/null
    echo "        Done."
fi
if command -v git &>/dev/null; then
    echo "    Git is installed"
else
    echo "    Installing git..."
    sudo sudo apt-get install git -qq > /dev/null
    echo "        Done."
fi
if command -v brotli &>/dev/null; then
    echo "    Brotli is installed"
else
    echo "    Installing brotli..."
    sudo sudo apt-get install brotli -qq > /dev/null
    echo "        Done."
fi
echo "Downloading program..."
mkdir files
cd files
git clone https://github.com/LiteApplication/rom-unzip.git --quiet
echo "    Done"
cd ..
mkdir rom
sudo python3 ./files/src/main.py
exit 0
