#!/bin/bash
VERSION="0.1"
echo "Welcome to ROM Unzipper by LiteApplication"
if (whoami != root)
  then echo "You have to run this script as root. \n Try sudo ./1click"
  exit 1

echo "Checking dependances..."
if command -v python3 &>/dev/null; then
    echo "    Python 3 is installed"
else
    echo "    Installing python3..."
    sudo sudo apt-get install python3 python -qq > /dev/null
    echo "        Done."
fi
if command -v brotli &>/dev/null; then
    echo "    Brotli is installed"
else
    echo "    Installing brotli..."
    sudo sudo apt-get install brotli -qq > /dev/null
    echo "        Done."
fi
exit 0
