#!/usr/bin/python3
import os
import selectrom as sr
import sdat2img
from termcolor import colored
print("Welcome to ",colored("ROM-Unzip","blue"),"by LiteApplication")
rompath=sr.select(os.getcwd())
if rompath=="NOROM":
    print(colored("E02 : NoRomError, Please cd to the rom.zip folder","red"))
    exit(1)
if not os.path.isfile(rompath):
    print(colored("E03 : NotFileError, The selected ROM is not a file (" + rompath + ").Please cd to the rom.zip folder and select it. ","red"))
    exit(1)
os.chdir(glob.glob("rom-extracted"))
print("Extracting system.new.dat.br...")
sr.unbr("system.new.dat.br","system.new.dat")
print("Extracting vendor.new.dat.br...")
sr.unbr("vendor.new.dat.br","vendor.new.dat")
print("Removing useless files...")
sdat2img.extract("system.new.dat","system.transfer.list","system.img")
sdat2img.extract("vendor.new.dat","vendor.transfer.list","vendor.img")
print("Mounting system.img ...")
os.system("mkdir system.dir")
os.system("sudo mount -t ext4 -o loop system.img system.dir/")
print("Mounting vendor.img ...")
os.system("mkdir vendor.dir")
os.system("sudo mount -t ext4 -o loop vendor.img vendor.dir/")
print("Saving permissions for system...")
for path in romExtractor
